### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#3]
Projects images to be the same size
<img width="1255" alt="Screen Shot 2019-11-12 at 11 05 09 am" src="https://user-images.githubusercontent.com/55725505/68630736-588c7c80-053c-11ea-994d-8de15d9256a1.png">

**Comment by markendley** [comment]
fixed

**Comment by Jakestudiofriday** [comment]
Not fixed - can you send us a screen shot of changes like this? As we are not seeing what you are.

**Comment by markendley** [comment]
![Screen Shot 2019-11-20 at 1 03 14 pm](https://user-images.githubusercontent.com/6570606/69202555-227f7600-0b96-11ea-9b96-87ce6a2389fa.png)

**Comment by markendley** [comment]
oh, you have a RETINA screen

**Comment by markendley** [comment]
You need to upload images 1800 x 1410 pixels.

OR I can turn retina support off
