### ISSUE TITLE
Safari and Chrome

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#30]
Are displaying the site differently
<img width="1235" alt="Screen Shot 2020-01-22 at 11 26 26 am" src="https://user-images.githubusercontent.com/55725505/72855028-48e29e80-3d0a-11ea-9915-248654b37ed2.png">
<img width="1275" alt="Screen Shot 2020-01-22 at 11 27 13 am" src="https://user-images.githubusercontent.com/55725505/72855035-4d0ebc00-3d0a-11ea-9174-2104d4bf59f6.png">

**Comment by markendley** [comment]
No, those are just different images. 

But I can see that you just don't want the image to overlap the logo?

**Comment by LaraStudioFriday** [comment]
I know they are different images - yes - we don't want the image to overlap the logo

<img width="1270" alt="Screen Shot 2020-01-23 at 8 44 19 am" src="https://user-images.githubusercontent.com/55725505/72937130-a20b0a80-3dbc-11ea-8cd6-09d78d1130b8.png">

Chrome shows correctly

**Comment by markendley** [comment]
I can make Chrome and Safari behave the same way, but the problem is, I can't prevent portait images from overlapping the logo (especially on the smaller screens).

the best way around it would be to put a background behind the nav (not a trancluent white thought)

Or we can remove the logo for these pages?

**Comment by LaraStudioFriday** [comment]
Can we just make the images smaller on safari? see video

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Ive cleared browsing history and even gone private mode - but still seeing them same as before! 
<img width="1267" alt="Screen Shot 2020-01-29 at 6 18 26 pm" src="https://user-images.githubusercontent.com/55725505/73335532-c9ce0700-42c3-11ea-962b-c9f06771394d.png">

**Comment by LaraStudioFriday** [comment]
and now chrome is wrong...yes cleared cache
<img width="1276" alt="Screen Shot 2020-01-29 at 6 26 39 pm" src="https://user-images.githubusercontent.com/55725505/73336110-10703100-42c5-11ea-8322-85a946304101.png">

**Comment by markendley** [comment]
rebuilt the slider, I gurantee that size issue won't be a problem
